services:
  backend:
    build:
      context: .
      dockerfile: src/backend/Dockerfile
    container_name: tubes2_tuak_backend
    environment:
      HOST: 0.0.0.0
      PORT: 3000
    ports:
      - "3000:3000"

  frontend:
    build:
      context: .
      dockerfile: src/frontend/Dockerfile
    container_name: tubes2_tuak_frontend
    depends_on:
      - backend
    ports:
      - "80:80"
